#include "WebGL.hpp"
#include "GameWindow.hpp"
#include "Supervisor.hpp"
#include "utils.hpp"
#include <cstring>
#include <new>
#include <unordered_set>

// Provided for anyone who wants to recompile with new shaders without rerunning the premake script
#ifdef USE_C23_EMBED
static const char fragShaderBytes[] = {
#embed "ff.frag"
    , '\0'};

static const char vertShaderBytes[] = {
#embed "ff.vert"
    , '\0'};
#else
#include "autogenerated/Embeds.hpp"
#endif

#define POSITION_ATTRIBUTE_INDEX 0
#define TEX_COORDS_ATTRIBUTE_INDEX 1
#define DIFFUSE_ATTRIBUTE_INDEX 2

GLuint createShader(const char *source, GLenum type, const char *descString, bool glesContext,
                    std::unordered_set<GlShaderUniform> &omittedUniforms)
{
    const char *fullShaderSource[32];
    GLint getRet = 0;
    GLuint shaderHandle = g_glFuncTable.glCreateShader(type);
    u32 shaderSourceIndex = 1;

    if (shaderHandle == 0)
    {
        goto fail;
    }

    // There are platforms (eg. macOS) where, even when ES 2.0 context
    // is requested, 2.1 is returned.
    // This adds a preamble which is slightly different between ES 2.0 and 2.1.
    if (glesContext)
    {
        fullShaderSource[0] = "#version 100\n"
                              "precision mediump float;\n";

        if (SDL_GL_ExtensionSupported("GL_EXT_frag_depth"))
        {
            fullShaderSource[shaderSourceIndex++] = "#extension GL_EXT_frag_depth : require\n";
            fullShaderSource[shaderSourceIndex++] = "#define USE_FRAG_DEPTH\n";
        }
    }
    else
    {
        fullShaderSource[0] = "#version 120\n"
                              "#define gl_FragDepthEXT gl_FragDepth\n";
        fullShaderSource[shaderSourceIndex++] = "#define USE_FRAG_DEPTH\n";
    }

    if (g_Supervisor.cfg.opts & (1 << GCOS_DONT_USE_FOG))
    {
        fullShaderSource[shaderSourceIndex++] = "#define NO_FOG\n";
        omittedUniforms.insert(UNIFORM_FOG_NEAR);
        omittedUniforms.insert(UNIFORM_FOG_FAR);
        omittedUniforms.insert(UNIFORM_FOG_COLOR);
    }

    if (g_Supervisor.cfg.opts & (1 << GCOS_DONT_USE_VERTEX_BUF))
    {
        fullShaderSource[shaderSourceIndex++] = "#define NO_VERTEX_BUFFER\n";
    }
    else
    {
        omittedUniforms.insert(UNIFORM_ENV_DIFFUSE);
    }

    fullShaderSource[shaderSourceIndex] = source;

    g_glFuncTable.glShaderSource(shaderHandle, shaderSourceIndex + 1, fullShaderSource, NULL);
    g_glFuncTable.glCompileShader(shaderHandle);

    g_glFuncTable.glGetShaderiv(shaderHandle, GL_COMPILE_STATUS, &getRet);

    if (getRet)
    {
        return shaderHandle;
    }

    g_glFuncTable.glGetShaderiv(shaderHandle, GL_INFO_LOG_LENGTH, &getRet);

    if (getRet == 0)
    {
        utils::DebugPrint("Shader %s compilation failed and has no log!\n", descString);
    }
    else
    {
        char *log = new char[getRet];
        g_glFuncTable.glGetShaderInfoLog(shaderHandle, getRet, NULL, log);
        utils::DebugPrint("Shader %s compilation failed, log: \n%s", descString, log);
        delete[] log;
    }

fail:
    return 0;
}

bool linkProgram(GLuint programHandle)
{
    g_glFuncTable.glLinkProgram(programHandle);

    GLint getRet;

    g_glFuncTable.glGetProgramiv(programHandle, GL_LINK_STATUS, &getRet);

    if (getRet)
    {
        return true;
    }

    g_glFuncTable.glGetProgramiv(programHandle, GL_INFO_LOG_LENGTH, &getRet);

    if (getRet == 0)
    {
        utils::DebugPrint("Program link failed and has no log!");
        return false;
    }

    char *log = new char[getRet];
    g_glFuncTable.glGetProgramInfoLog(programHandle, getRet, NULL, log);
    utils::DebugPrint("Program link failed, log: \n%s", log);
    delete[] log;

    return false;
}

void WebGL::SetContextFlags()
{
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
}

GfxInterface *WebGL::Create()
{
    WebGL *interface = new WebGL;

    SetContextFlags();

    SDL_Init(SDL_INIT_VIDEO);

    u32 flags = SDL_WINDOW_OPENGL;
    i32 height = GAME_WINDOW_HEIGHT_REAL;
    i32 width = GAME_WINDOW_WIDTH_REAL;
    i32 x = SDL_WINDOWPOS_UNDEFINED;
    i32 y = SDL_WINDOWPOS_UNDEFINED;

    if (g_Supervisor.cfg.windowed == 0)
    {
        flags |= SDL_WINDOW_FULLSCREEN_DESKTOP;
        width = 640;
        height = 480;
    }

    SDL_Window *window = SDL_CreateWindow(TH_WINDOW_TITLE, x, y, width, height, flags);
    interface->window = window;
    if (window == NULL)
    {
        delete interface;
        return NULL;
    }

    SDL_GLContext glContext = SDL_GL_CreateContext(window);
    interface->glContext = glContext;
    if (glContext == NULL)
    {
        delete interface;
        return NULL;
    }

    if (SDL_GL_MakeCurrent(window, glContext) != 0)
    {
        delete interface;
        return NULL;
    }

    SDL_GL_SetSwapInterval(1);

    i32 drawableW, drawableH;
    SDL_GL_GetDrawableSize(window, &drawableW, &drawableH);
    f32 scaleX = (f32)drawableW / GAME_WINDOW_WIDTH;
    f32 scaleY = (f32)drawableH / GAME_WINDOW_HEIGHT;
    interface->viewportScale = scaleX < scaleY ? scaleX : scaleY;
    interface->viewportOffsetX = ((f32)drawableW - GAME_WINDOW_WIDTH * interface->viewportScale) / 2.0f;
    interface->viewportOffsetY = ((f32)drawableH - GAME_WINDOW_HEIGHT * interface->viewportScale) / 2.0f;

    // The ES profile request is not always honored,
    // so check if we really got it or the desktop one.
    const GLubyte *(GLAPIENTRY * getString)(GLenum) =
        (const GLubyte *(GLAPIENTRY *)(GLenum))SDL_GL_GetProcAddress("glGetString");
    const char *glVersion = getString != NULL ? (const char *)getString(GL_VERSION) : NULL;
    interface->glesContext = glVersion != NULL && std::strncmp(glVersion, "OpenGL ES", 9) == 0;

    utils::DebugPrint("Got a %s context (GL_VERSION: %s)\n", interface->glesContext ? "GL ES" : "desktop GL",
                      glVersion != NULL ? glVersion : "unknown");

    g_glFuncTable.ResolveFunctions(interface->glesContext);

    if (!interface->Init())
    {
        delete interface;
        return NULL;
    }

    return interface;
}

void WebGL::Exit()
{
    if (this->glContext)
    {
        SDL_GL_DeleteContext(this->glContext);
        this->glContext = NULL;
    }
    if (this->window)
    {
        SDL_DestroyWindow(this->window);
        this->window = NULL;
    }
}

bool WebGL::Init()
{
    ZunMatrix identityMatrix;
    std::unordered_set<GlShaderUniform> omittedUniforms;

    while (g_glFuncTable.glGetError() != GL_NO_ERROR)
    {
    }

    // Using a hashset for this is definitely super overkill, but it still feels more right
    //   than just using a vector or C array

    this->vertexShaderHandle =
        createShader(vertShaderBytes, GL_VERTEX_SHADER, "vertex", this->glesContext, omittedUniforms);
    this->fragmentShaderHandle =
        createShader(fragShaderBytes, GL_FRAGMENT_SHADER, "fragment", this->glesContext, omittedUniforms);
    this->programHandle = g_glFuncTable.glCreateProgram();

    if (this->vertexShaderHandle == 0 || this->fragmentShaderHandle == 0 || this->programHandle == 0)
    {
        goto fail;
    }

    g_glFuncTable.glAttachShader(this->programHandle, this->vertexShaderHandle);
    g_glFuncTable.glAttachShader(this->programHandle, this->fragmentShaderHandle);

    g_glFuncTable.glBindAttribLocation(this->programHandle, POSITION_ATTRIBUTE_INDEX, "position");
    g_glFuncTable.glBindAttribLocation(this->programHandle, TEX_COORDS_ATTRIBUTE_INDEX, "texCoords");
    g_glFuncTable.glBindAttribLocation(this->programHandle, DIFFUSE_ATTRIBUTE_INDEX, "diffuse");

    if (!linkProgram(this->programHandle))
    {
        goto fail;
    }

    g_glFuncTable.glUseProgram(this->programHandle);

    this->uniforms[UNIFORM_MODELVIEW] = g_glFuncTable.glGetUniformLocation(programHandle, "modelviewMatrix");
    this->uniforms[UNIFORM_PROJECTION] = g_glFuncTable.glGetUniformLocation(programHandle, "projectionMatrix");
    this->uniforms[UNIFORM_TEXTURE_MATRIX] = g_glFuncTable.glGetUniformLocation(programHandle, "textureMatrix");

    this->uniforms[UNIFORM_ENV_DIFFUSE] = g_glFuncTable.glGetUniformLocation(programHandle, "envDiffuse");
    this->uniforms[UNIFORM_TEX_COORD_FLAG] = g_glFuncTable.glGetUniformLocation(programHandle, "useTexCoords");
    this->uniforms[UNIFORM_DIFFUSE_FLAG] = g_glFuncTable.glGetUniformLocation(programHandle, "useDiffuse");
    this->uniforms[UNIFORM_TEXTURE_SAMPLER] = g_glFuncTable.glGetUniformLocation(programHandle, "tex");
    this->uniforms[UNIFORM_FOG_NEAR] = g_glFuncTable.glGetUniformLocation(programHandle, "fogNear");
    this->uniforms[UNIFORM_FOG_FAR] = g_glFuncTable.glGetUniformLocation(programHandle, "fogFar");
    this->uniforms[UNIFORM_FOG_COLOR] = g_glFuncTable.glGetUniformLocation(programHandle, "fogColor");
    this->uniforms[UNIFORM_COLOR_OP] = g_glFuncTable.glGetUniformLocation(programHandle, "colorOp");

    for (u32 i = 0; i < ARRAY_SIZE(this->uniforms); i++)
    {
        if (this->uniforms[i] == -1 && omittedUniforms.count((GlShaderUniform)i) != 0)
        {
            utils::DebugPrint("Get uniform %i location failed!", i);
        }
    }

    // Use texture unit 0 (aka the only one we ever use)
    g_glFuncTable.glUniform1i(this->uniforms[UNIFORM_TEXTURE_SAMPLER], 0);

    identityMatrix.Identity();
    g_glFuncTable.glUniformMatrix4fv(this->uniforms[UNIFORM_MODELVIEW], 1, false, (GLfloat *)&identityMatrix.m);
    g_glFuncTable.glUniformMatrix4fv(this->uniforms[UNIFORM_PROJECTION], 1, false, (GLfloat *)&identityMatrix.m);
    g_glFuncTable.glUniformMatrix4fv(this->uniforms[UNIFORM_TEXTURE_MATRIX], 1, false, (GLfloat *)&identityMatrix.m);

    g_glFuncTable.glUniform1f(this->uniforms[UNIFORM_FOG_FAR], 1.0f);

    g_glFuncTable.glEnableVertexAttribArray(POSITION_ATTRIBUTE_INDEX);

    return true;
fail:
    utils::DebugPrint("GL error: %X\n", g_glFuncTable.glGetError());
    g_glFuncTable.glDeleteProgram(this->programHandle);
    g_glFuncTable.glDeleteShader(this->vertexShaderHandle);
    g_glFuncTable.glDeleteShader(this->fragmentShaderHandle);

    return false;
}

void WebGL::SetFogRange(f32 nearPlane, f32 farPlane)
{
    g_glFuncTable.glUniform1f(this->uniforms[UNIFORM_FOG_NEAR], nearPlane);
    g_glFuncTable.glUniform1f(this->uniforms[UNIFORM_FOG_FAR], farPlane);
}

void WebGL::SetFogColor(ZunColor color)
{
    g_glFuncTable.glUniform4f(this->uniforms[UNIFORM_FOG_COLOR], ((color >> 16) & 0xFF) / 255.0f,
                              ((color >> 8) & 0xFF) / 255.0f, (color & 0xFF) / 255.0f, ((color >> 24) & 0xFF) / 255.0f);
}

void WebGL::ToggleVertexAttribute(u8 attr, bool enable)
{
    if (attr & VERTEX_ATTR_TEX_COORD)
    {
        if (enable)
        {
            g_glFuncTable.glEnableVertexAttribArray(TEX_COORDS_ATTRIBUTE_INDEX);
            g_glFuncTable.glUniform1i(this->uniforms[UNIFORM_TEX_COORD_FLAG], true);
        }
        else
        {
            g_glFuncTable.glDisableVertexAttribArray(TEX_COORDS_ATTRIBUTE_INDEX);
            g_glFuncTable.glUniform1i(this->uniforms[UNIFORM_TEX_COORD_FLAG], false);
        }
    }

    if (attr & VERTEX_ATTR_DIFFUSE)
    {
        if (enable)
        {
            g_glFuncTable.glEnableVertexAttribArray(DIFFUSE_ATTRIBUTE_INDEX);
            g_glFuncTable.glUniform1i(this->uniforms[UNIFORM_DIFFUSE_FLAG], true);
        }
        else
        {
            g_glFuncTable.glDisableVertexAttribArray(DIFFUSE_ATTRIBUTE_INDEX);
            g_glFuncTable.glUniform1i(this->uniforms[UNIFORM_DIFFUSE_FLAG], false);
        }
    }
}

void WebGL::SetAttributePointer(VertexAttributeArrays attr, std::size_t stride, void *ptr)
{
    switch (attr)
    {
    case VERTEX_ARRAY_POSITION:
        g_glFuncTable.glVertexAttribPointer(POSITION_ATTRIBUTE_INDEX, 3, GL_FLOAT, false, stride, ptr);
        break;
    case VERTEX_ARRAY_TEX_COORD:
        g_glFuncTable.glVertexAttribPointer(TEX_COORDS_ATTRIBUTE_INDEX, 2, GL_FLOAT, false, stride, ptr);
        break;
    case VERTEX_ARRAY_DIFFUSE:
        g_glFuncTable.glVertexAttribPointer(DIFFUSE_ATTRIBUTE_INDEX, 4, GL_UNSIGNED_BYTE, true, stride, ptr);
        break;
    }
}

void WebGL::SetColorOp(TextureOpComponent component, ColorOp op)
{
    if (component == COMPONENT_ALPHA)
    {
        return;
    }

    g_glFuncTable.glUniform1i(this->uniforms[UNIFORM_COLOR_OP], op);
}

void WebGL::SetTextureFactor(ZunColor factor)
{
    g_glFuncTable.glUniform4f(this->uniforms[UNIFORM_ENV_DIFFUSE], ((factor >> 16) & 0xFF) / 255.0f,
                              ((factor >> 8) & 0xFF) / 255.0f, (factor & 0xFF) / 255.0f,
                              ((factor >> 24) & 0xFF) / 255.0f);
}

void WebGL::SetTransformMatrix(TransformMatrix type, const ZunMatrix &matrix)
{
    // I should probably just remove the model matrix from the range of possibilies
    static const u32 matrixUniformEnum[4] = {UNIFORM_MODELVIEW, UNIFORM_MODELVIEW, UNIFORM_PROJECTION,
                                             UNIFORM_TEXTURE_MATRIX};

    g_glFuncTable.glUniformMatrix4fv(this->uniforms[matrixUniformEnum[type]], 1, false, (const GLfloat *)&matrix.m);
}

void WebGL::Enable(Capabilities cap)
{
    switch (cap)
    {
    case CAPS_BLEND:
        g_glFuncTable.glEnable(GL_BLEND);
        break;
    case CAPS_DEPTH_TEST:
        g_glFuncTable.glEnable(GL_DEPTH_TEST);
        break;
    }
}

bool WebGL::HasError()
{
    return g_glFuncTable.glGetError() != GL_NO_ERROR;
}

void WebGL::SetTextureFilter()
{
    g_glFuncTable.glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
}

void WebGL::GetViewport(u32 *viewport)
{
    g_glFuncTable.glGetIntegerv(GL_VIEWPORT, (GLint *)viewport);
    viewport[0] = (u32)(((i32)viewport[0] - viewportOffsetX) / viewportScale);
    viewport[1] = (u32)(((i32)viewport[1] - viewportOffsetY) / viewportScale);
    viewport[2] = (u32)((i32)viewport[2] / viewportScale);
    viewport[3] = (u32)((i32)viewport[3] / viewportScale);
}

void WebGL::GetDepthRange(f32 *depthRange)
{
    g_glFuncTable.glGetFloatv(GL_DEPTH_RANGE, depthRange);
}

void WebGL::SetViewport(i32 x, i32 y, i32 width, i32 height)
{
    g_glFuncTable.glViewport(
        (i32)(x * viewportScale + viewportOffsetX),
        (i32)(y * viewportScale + viewportOffsetY),
        (i32)(width * viewportScale),
        (i32)(height * viewportScale));
}

void WebGL::SetDepthRange(f32 nearPlane, f32 farPlane)
{
    g_glFuncTable.glDepthRangef(nearPlane, farPlane);
}

void WebGL::SetBlendMode(BlendMode mode)
{
    if (mode == BLEND_INV_SRC_ALPHA)
    {
        g_glFuncTable.glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
    }
    else
    {
        g_glFuncTable.glBlendFunc(GL_SRC_ALPHA, GL_ONE);
    }
}

void WebGL::SetClearDepth(f32 depth)
{
    g_glFuncTable.glClearDepthf(depth);
}

void WebGL::SetClearColor(f32 r, f32 g, f32 b, f32 a)
{
    g_glFuncTable.glClearColor(r, g, b, a);
}

void WebGL::Clear(u32 clearBits)
{
    GLbitfield mask = 0;

    if (clearBits & CLEAR_COLOR_BUFFER)
        mask |= GL_COLOR_BUFFER_BIT;
    if (clearBits & CLEAR_DEPTH_BUFFER)
        mask |= GL_DEPTH_BUFFER_BIT;

    g_glFuncTable.glClear(mask);
}

void WebGL::SetDepthMask(bool enable)
{
    g_glFuncTable.glDepthMask(enable);
}

void WebGL::SetDepthFunc(DepthFunc func)
{
    if (func == DEPTH_FUNC_ALWAYS)
    {
        g_glFuncTable.glDepthFunc(GL_ALWAYS);
    }
    else
    {
        g_glFuncTable.glDepthFunc(GL_LEQUAL);
    }
}
GfxTextureHandle WebGL::CreateTexture()
{
    GLuint texture;
    g_glFuncTable.glGenTextures(1, &texture);
    return texture;
}

void WebGL::BindTexture(GfxTextureHandle handle)
{
    g_glFuncTable.glBindTexture(GL_TEXTURE_2D, handle);
}

void WebGL::DeleteTexture(GfxTextureHandle handle)
{
    g_glFuncTable.glDeleteTextures(1, (GLuint *)&handle);
}

void WebGL::SetTextureImage(u32 width, u32 height, PixelFormat fmt, PixelDataType type, const void *data)
{
    GLenum glFmt;
    GLenum glType;

    switch (fmt)
    {
    case PIXEL_RGBA:
        glFmt = GL_RGBA;
        break;
    case PIXEL_RGB:
        glFmt = GL_RGB;
        break;
    }

    switch (type)
    {
    case PIXEL_UNSIGNED_BYTE:
        glType = GL_UNSIGNED_BYTE;
        break;
    case PIXEL_UNSIGNED_SHORT_5_5_5_1:
        glType = GL_UNSIGNED_SHORT_5_5_5_1;
        break;
    case PIXEL_UNSIGNED_SHORT_5_6_5:
        glType = GL_UNSIGNED_SHORT_5_6_5;
        break;
    case PIXEL_UNSIGNED_SHORT_4_4_4_4:
        glType = GL_UNSIGNED_SHORT_4_4_4_4;
        break;
    }

    g_glFuncTable.glTexImage2D(GL_TEXTURE_2D, 0, glFmt, width, height, 0, glFmt, glType, data);
}

void WebGL::SetTextureSubImage(i32 xoffset, i32 yoffset, i32 width, i32 height, const void *data)
{
    g_glFuncTable.glTexSubImage2D(GL_TEXTURE_2D, 0, xoffset, yoffset, width, height, GL_RGB, GL_UNSIGNED_BYTE, data);
}

void WebGL::ReadPixels(i32 x, i32 y, i32 width, i32 height, const void *pixels)
{
    g_glFuncTable.glReadPixels(x, y, width, height, GL_RGBA, GL_UNSIGNED_BYTE, (void *)pixels);
}

void WebGL::Draw(PrimitiveType type, i32 start, i32 count)
{
    GLenum glPrim;

    switch (type)
    {
    case PRIM_TRIANGLE_STRIP:
        glPrim = GL_TRIANGLE_STRIP;
        break;
    case PRIM_TRIANGLES:
        glPrim = GL_TRIANGLES;
        break;
    }

    g_glFuncTable.glDrawArrays(glPrim, start, count);
}

void WebGL::SwapBuffers()
{
    SDL_GL_SwapWindow(window);
}
